### ISSUE TITLE
Jabber MUC won't let me in!

### ISSUE THREAD

**Issue by l29ah** [russian-meshnet/influence#1]
> Jabber: influence_dev@conference.netwhood.online

Authorization error (Registration required): Membership is required to enter this room

**Comment by ChronosX88** [comment]
To access the room, you must register on the server.

**Comment by whoizit** [comment]
@ChronosX88 sounds weird

**Comment by ChronosX88** [comment]
What's so strange about that?

**Comment by whoizit** [comment]
the whole xmpp network seems to be open, but you have made your server closed. I do not understand why.

**Comment by ChronosX88** [comment]
It is not my server. Please, contact [@abslimit](https://t.me/abslimit) for that matter, he owns the server.

**Comment by l29ah** [comment]
The address wasn’t understood

Pale Moon doesn't know how to open this address, because the protocol (tg) isn't associated with any program.

**Comment by l29ah** [comment]
Consider switching to a saner server then. Say, `bitcheese.net`.

**Comment by ChronosX88** [comment]
> The address wasn’t understood
> 
> Pale Moon doesn't know how to open this address, because the protocol (tg) isn't associated with any program.

@abslimit in Telegram

> Consider switching to a saner server then. Say, `bitcheese.net`.
I'll think about this offer.

**Comment by l29ah** [comment]
How do i send him a message w/o buying a GSM ID?

**Comment by ChronosX88** [comment]
I do not know how to help you.
